#!/bin/bash
# The job name
#SBATCH --job-name=helloworld
# Set the error and output files
#SBATCH --output=output.out
#SBATCH --error=error.out
# Set the initial working directory
#SBATCH --chdir=/ec/res4/scratch/nkac/hm_home/BL2_n0_2500m/output
# Choose the queue
#SBATCH --qos=ns
# Wall clock time limit
#SBATCH --time=00:05:00
# Send an email on failure
#SBATCH --mail-type=FAIL
gl -nc ICMSHHARM032022070106 -o nc03_202207 -n mergedim

# Setup 'gl' as an ALIAS, pointing to gl binary.
